on:
  workflow_dispatch:
    inputs:
      which:
        type: choice
        description: Which dependents to check
        options:
          - strong
          - most

name: Reverse dependency check

jobs:
  revdep_check:
    name: Reverse check ${{ inputs.which }} dependents
    uses: r-devel/recheck/.github/workflows/recheck.yml@v1
    with:
      which: ${{ inputs.which }}
      subdirectory: '' # set if your R package is in a subdir of the git repo
      repository: '' # set to recheck an R package from another git repo
      ref: '' # set to recheck a custom tag/branch from another repo